# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjdhM2VjYjg0MWI1NmE4Nzg2ZWEyMWIxYWJlOWI4OTVhYTUwYzc5MzEzMDQ3MGFiYTkwMWVmZTYzZTMwZjU2Mjc2ZmMwNGM2NWNkYzE3YWI5YzAyZDJhOGFiNjkwMGNlZDczOWU0MmU1N2QxZGMzNWFmZWUwZDMxYmRhY2Y3YmE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
